### PR TITLE
Create a Makefile

### PR DESCRIPTION
**Pull request by williamthome**
# Description

I always forget to run the npm CI command, and I think it's better to combine multiple related commands into one. Therefore, I'd like to suggest considering implementing a Makefile for this purpose. To run both CI commands, simply run `make` or `make ci`.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/arizona-framework/arizona/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I can accept this, but I'm not a huge fan of `Makefile` mixed with `rebar3`. Now I gotta remember a different set of commands and they're not in my go-to place, which would be `rebar.config`.

**Comment by paulo-ferraz-oliveira** [comment]
How about a pre-compile hook?

```
{pre_hooks, [
    {compile, "npm run ci"}
]}.
```

(put that in your `rebar.config`)

Try it out and lemme know.

**Comment by williamthome** [comment]
> Try it out and lemme know.

It causes a loop. The same goes for `app_compile` hook.

**Comment by paulo-ferraz-oliveira** [comment]
I'd prefer to not include this at this moment; it's an extra dependency and element for little gain. If we see that it's a big hassle we could, in the future. Otherwise, that's what CI's there for, so we don't forget what to run. What do you say?

**Comment by williamthome** [comment]
No worries. I'm closing this PR to ensure that we're all on the same page.

**Comment by paulo-ferraz-oliveira** [comment]
If we end up doing it, here's a Gist for improving the Makefile: https://gist.github.com/paulo-ferraz-oliveira/cd508d47f6def318e62137ee2025aeaa

**Pull request closed without merging**
